### ISSUE TITLE
Mautic webhook performance

### ISSUE THREAD

**Issue by pety-dc** [verygoodplugins/wp-fusion-lite#14]
Hey VeryGoodPlugins!

We are using the wp-fusion plugin for WP with Mautic. 
We set up a webhook in mautic to send data to Wordpress each time the contact is updated.

We are concerned about the performance of the webhooks. As far as I know by default WP fusion does not use the data it gets from the webhook call to perform the update, but rather starts an api call to pull the data from the CRM.
In our case if the visitor fills a form, mautic processes that request.
Then mautic invokes the webhook and starts a request to WP-fusion.
Then Wp-fusion sends an api request to mautic to pull the data.

I'm aware that both mautic and WP-fusion are capable of queuing/buffering the webhook calls. But unfortunately the data-sharing cannot be delayed. All the 3 above requests bouncing between wordpress and mautic are synchronous and thus holding the original request started by the visitor occasionally for several seconds. 

I've found a workaround in the `activecampaign`  CRM driver. Namely the `quick_update_tags` feature, which according to the comment makes the `update_tags` webhook call use the data it gets and omit the api call. 

Would you implement it for Mautic too?

**Comment by jack-arturo** [comment]
Hey @pety-dc ,

I know what you mean. It's a bit tricky.

In the full version of WP Fusion we did recently update the way the webhook handler works. I think you have a license to the full version (?), if not let me know and I can commit that change up here to WPF Lite so you can try it out.

With that change any integration can return a `tags` array key from the `format_post_data()` function. For example with ActiveCampaign that now looks like:

```php
public function format_post_data( $post_data ) {

	if ( isset( $post_data['contact']['id'] ) ) {
		$post_data['contact_id'] = $post_data['contact']['id'];
	}

	if ( ! empty( $post_data['contact']['tags'] ) ) {
		$post_data['tags'] = explode( ', ', $post_data['contact']['tags'] );
	}

	return $post_data;

}
```

We could do the same for Mautic easily enough, like

`$post_data['tags'] = (array) $payload->{'mautic.lead_post_save_update'}[0]->contact->tags;`

If that'd be helpful we can make that change, no problem.

But.... that's just the tags. I can't think of a secure way to load the contact metadata out of a webhook.

With the way we have it now, even if a malicious actor knew your `access_key` and a valid Mautic contact ID, the only thing they could do by visiting the webhook URL is force a load of the data that's already on that contact's record in Mautic.

If we read the contact data directly out of the webhook data and save it to the database, even with sanitization, a malicious actor could POST a payload like:

'user_email' => 'badguy@example.com',
'user_pass' => 'ImInControlNow'

and if those fields were enabled for sync, they could take over any user's account.

You certainly could add an extra webhook listener for that on top of our existing APIs. But it's not something we could include in WP Fusion proper due to that security issue.

Unless you have an idea of how we could load the data without needing to connect back to Mautic, while being secure? I'm open to suggestions.

**Comment by pety-dc** [comment]
Hey VeryGoodPlugins!

Thanks for the quick answer!

I understand your security concerns. In fact, fortunately we only need tags updated instantly and preferably quickly.

So if you added that line to to mautic's `format_post_data`
`$post_data['tags'] = (array) $payload->{'mautic.lead_post_save_update'}[0]->contact->tags;`

... then `update_tags` webhook call would omit api calls to update tags just like in the case of `activecampaign`?



As for secure webhook data transfer I can only imagine solutions. For example the webhook sender could include a hash created from the sent data and sealed with a private key. The public key should be available in the DNS of the sender. The receiver then could check by decoding the included hash with the public key whether the package was truly sent by the server the packege claims to originate from. At least this is how DKIM works.
But I don't think, any CRM would provide such secure methods to encode webhook data.

**Comment by jack-arturo** [comment]
Cool, no problem, we can do that.

v3.36.2 of the full version was just released with support for "quick update" tags with Mautic. That works with the `update_tags` API endpoint, and requires zero APIs call back to Mautic.

With the `update` API endpoint, it will load the tags out of the payload, but still make an API call back to Mautic to load the user's metadata (due to the aforementioned security concerns). So it now makes one API call instead of two.

**Comment by pety-dc** [comment]
Hey VeryGoodPlugins!

Thank for the quick reply!

Mautic show how long each webhook call lasts.
Yesterday I set up an `update_tags` webhook call to see how faster it is than `update`. 
Today I installed the new `v3.36.2` version to see how much faster a webhook call became after the update. 

You said that 
> That works with the update_tags API endpoint, and requires zero APIs call back to Mautic.
But the time required to perform the webhook calls didn't change.

I might misunderstood something. It seems that the  `update_tags` updates the user's tags from the webhook data, and then still performs an api call. Thus tags appear in Wordpress a bit faster, but the webhook call is not faster overall.

Is there a way to enable the `quick` function? 
Judging by the source code of the webhook api the `update_tags` method does exactly that. If  `tags` is present in the $post_data it sets it to the user, then the `do_action` seems to still perform an `update_tags`

Did I miss something?

**Comment by jack-arturo** [comment]
@pety-dc ,

Ah, no, you're right.....

We also added an extra sanitize_text_field at the last minute, to protect against SQL injection. That's stripping out the tags. Which causes it to make an API call, as a fallback.

We have that fixed for Monday's update but if you want to try it out in the meantime just open up class WPF_API and comment out the line

`$post_data = array_map( 'sanitize_text_field', $post_data );`

And that will let the tags go through.

I did just test it all the way through with an `update_tags` webhook and the total time to handle it is now 0.017s. Pretty quick!

**Comment by pety-dc** [comment]
@verygoodplugins 

Yeah, commenting out the "sanitize" line did improve request time.
I think I'll wait for the next update. I don't wish to screw around with the source code without you supervising it.


But... **0.017s**? That's really quick!
From our mautic instance to our wordpress@kinsta the webhook takes ~0.5s even with "sanitize" line commented out. (1-1.2s otherwise)

**Comment by jack-arturo** [comment]
@pety-dc Awesome

I timed it just from the start of the `handle_webhooks()` function to the `die()`, that's why it's so fast. Wanted to make sure no API calls were being sent. Yeah I'm about 0.5s for the whole process as well (on Digital Ocean) 🙂

**Comment by pety-dc** [comment]
Ah, that's comforting :)
