### ISSUE TITLE
Make Bento CRM support defer'd loading

### ISSUE THREAD

**Issue by jessehanley** [verygoodplugins/wp-fusion-lite#21]
Hey WPFusion friends, 

We had a customer who is happily using WPFusion + Bento and installed a speed optimization plugin which caused a slight issue with tracking. This plugin made all enqueued scripts, including Bento.js, load defer'd which meant the inline script firing off the first pageview did not work.

Bento.js supports and encourages `defer` loading now so I was wondering if we could patch the integration to: 

- [x] Load Bento.js `defer` and `async` by default.
- [x] Wrap the inline script [here](https://github.com/verygoodplugins/wp-fusion-lite/blob/2a3ce1f0b99a05aed681c06b0dca6215fdc8fc85/includes/crms/bento/class-bento.php#L165) in an event listener looking for `bento:ready`.

Example:
```html
<script src="https://app.bentonow.com/------ SITE UUID -----.js" defer async></script>
<script>
window.addEventListener("bento:ready", function () {
  if (typeof(bento$) != 'undefined') {
    bento$(function() {
        bento.identify("example@example.com");
        bento.view();
    });
  }
})
</script>
```

End result: users who aren't using performance plugins load a little faster due to defer'ing of the script + users who install a plugin which adds defer don't run into a silent issue. Win win!

**Comment by jack-arturo** [comment]
Thanks @jessehanley ! 

Good timing, it looks like this will be supported in WordPress 6.3, which is due to come out on August 8th: https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/.

We'll make the change and have it ready for that update 🙌 

I've added the `bento:ready` event listener for the next WPF update 👍

**Comment by jessehanley** [comment]
Legend. Ty 🫡
