### ISSUE TITLE
Deprecation Notice for \MailPoet\Models Namespace Code

### ISSUE THREAD

**Issue by pavel-mailpoet** [verygoodplugins/wp-fusion-lite#36]
I am a developer for the MailPoet WordPress plugin, and I wanted to bring an important update regarding the use of our internal code to your attention.

We have noticed that your project is [utilising code](https://github.com/verygoodplugins/wp-fusion-lite/blob/5d13590d06c80246e61e6b9aab2ea091935af29d/includes/crms/mailpoet/class-mailpoet.php#L315) within the \MailPoet\Models namespace. This code has been deprecated for some time and has been triggering warnings. It was not intended for external use. We have always provided a [public API](https://github.com/mailpoet/mailpoet/tree/trunk/doc).

We have prepared a [pull request](https://github.com/mailpoet/mailpoet/pull/5734) to remove this obsolete code entirely. This change is necessary to maintain MailPoet's integrity and performance. The pull request is ready and will be merged soon.

To avoid disruptions, please update your project to stop using the \MailPoet\Models namespace code instead of relying on our provided [public API](https://github.com/mailpoet/mailpoet/tree/trunk/doc). If this update is not made, your code will fail once the pull request is merged and the new version is released. We aim to release it within the next couple of weeks.

Thank you for your understanding and cooperation.

**Comment by jack-arturo** [comment]
Hey @pavel-mailpoet , thanks for reaching out.

We've reviewed the public API docs again but as far as I can see there's no way to update an existing subscriber. Can you point us towards how to do that without accessing `\MailPoet\Models\Subscriber::createOrUpdate()`?

Our customers need this functionality in case an existing subscriber updates their profile or fills out a form, they need the updated properties to sync to MailPoet.

**Comment by pavel-mailpoet** [comment]
Hi @verygoodplugins, can you be a bit more specific about the exact use case? What are the values you need to update? Is it the name of the subscriber? Or something else?

**Comment by jack-arturo** [comment]
@pavel-mailpoet Name is one example. If someone updates their profile in WordPress we'd like the updated name to be reflected in MailPoet.

Another common example might be that someone registers an account on a membership site, which creates a MailPoet subscriber with name and email address. They are then directed to an onboarding survey, for example via [our WSForm integration](https://wpfusion.com/documentation/lead-generation/ws-form/).

The answers to the questions on the onboarding survey need to be synced back to the existing subscriber record in MailPoet in order to personalize email communications or trigger automations.

For more information on how WP Fusion syncs data with email marketing tools, see https://wpfusion.com/documentation/getting-started/syncing-contact-fields/

**Comment by HenryCorkins** [comment]
Hi @pavel-mailpoet , thanks for your help! 

We just released the fix in the free Lite plugin, and the pro version will receive the update by the end of the week.

**Comment by pavel-mailpoet** [comment]
Thank you for letting us know. The update method has been merged but not yet released. It should go out on Tuesday, July 30.
